// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef contour_h
#define contour_h
#include <FL/Fl.H>
#include <msmvtl/tmatrix.h>
#include <FL/Fl_Double_Window.H>
#include <fl_gl_contour.h>
extern fl_gl_contour *ct3;
#include <FL/Fl_Group.H>
#include <FL/Fl_Slider.H>
extern Fl_Slider *sc;
extern Fl_Slider *_z;
#include <FL/Fl_Button.H>
#include<string.h>
#include<FL/Fl_File_Chooser.H>
extern Fl_Button *button_data;
extern Fl_Button *button_graph;
#include <FL/Fl_Input.H>
extern Fl_Input *_xyz_file;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *control_panel;
#include <FL/Fl_Choice.H>
extern Fl_Choice *ip;
extern Fl_Choice *pt;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *gx;
extern Fl_Value_Input *gy;
extern Fl_Value_Input *lv;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *_bx_d;
extern Fl_Check_Button *_ch_pl;
extern Fl_Check_Button *_ch_d;
extern Fl_Check_Button *_ch_sp;
extern Fl_Check_Button *_btt_2d;
extern Fl_Check_Button *_btt_3d;
extern Fl_Choice *g2d;
extern Fl_Choice *g3d;
extern Fl_Check_Button *_chk_avg;
extern Fl_Check_Button *_chk_del;
extern Fl_Value_Input *_tol;
extern Fl_Value_Input *gx1;
extern Fl_Value_Input *gy1;
extern Fl_Value_Input *gz1;
extern Fl_Value_Input *gx2;
extern Fl_Value_Input *gy2;
extern Fl_Value_Input *gz2;
extern Fl_Group *_sm_lm;
extern Fl_Value_Input *cgx1;
extern Fl_Value_Input *cgy1;
extern Fl_Value_Input *cgx2;
extern Fl_Value_Input *cgy2;
extern Fl_Button *_save_as;
extern Fl_Button *rs;
extern Fl_Check_Button *_chk_cut;
extern Fl_Check_Button *_chk_rf;
extern Fl_Menu_Item menu_ip[];
extern Fl_Menu_Item menu_pt[];
extern Fl_Menu_Item menu_g2d[];
extern Fl_Menu_Item menu_g3d[];
void load_xyz_data();
void build_graph();
#endif
